name: GitHub Actions Demo
on:
  workflow_dispatch:

jobs:
  ubuntu:
    runs-on: ubuntu-latest
    steps:
      - name: Test on Ubuntu
        shell: bash
        run: |
          a=YES
          if [ $a == "YES" ]; then
            echo test1
            echo test2
            echo test3
          fi
          echo end

  windows:
    runs-on: windows-2019
    steps:
      - name: Test on Windows
        shell: cmd
        run: |
          set "a=YES"
          echo start
          If /I "%a%" == "YES" (
            echo test1
            echo test2
            echo test3
          )
          echo end
  
  windows2:
    runs-on: windows-2019
    steps:
      - name: Test 2 on Windows
        shell: cmd
        run: |
          set "a=YES"
          echo start
          if "%a%" == "YES" (
            echo test1
            echo test2
            echo test3
          )
          echo end
  
  windows3:
    runs-on: windows-2019
    steps:
      - name: Test 3 on Windows
        shell: cmd
        run: |
          set a="YES"
          echo start
          if "%a%" == "YES" (
            echo test1
            echo test2
            echo test3
          )
          echo end
  
  windows4:
    runs-on: windows-2019
    steps:
      - name: Test 4 on Windows
        shell: cmd
        run: |
          echo test1
          set "myVar=YES"
          if "%myVar%" == "YES" (
            set "MSMPI_INC=C:\Program Files (x86)\Microsoft SDKs\MPI\Include\"
            set "MSMPI_LIB32=C:\Program Files (x86)\Microsoft SDKs\MPI\Lib\x86\"
            set "MSMPI_LIB64=C:\Program Files (x86)\Microsoft SDKs\MPI\Lib\x64\"
          )
          if "%myVar%" == "NO" (
            echo yahou
          )
          echo test2